### ISSUE TITLE
Support python 3.11 ?

### ISSUE THREAD

**Issue by nvuillam** [jruere/multiprocessing-logging#61] opened 2023-03-11 09:30 UTC
It seems that with Python 3.11, sometimes there is the following crash

```shell
  File "/usr/local/lib/python3.11/multiprocessing/connection.py", line 378, in _recv
    chunk = read(handle, remaining)
            ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object cannot be interpreted as an integer
```

You can see more details in https://github.com/oxsecurity/megalinter/issues/2425

Would it be possible to provide a fix ?

Many thanks ! :)

cc @llaville

**Comment by jruere** [comment] 2023-03-11 09:53
I'll look into it.

In the reference issue, the problem seems not to be in this package, we are just receiving from a queue. 

@nvuillam  Could you provide a small script to reproduce?

**Comment by nvuillam** [comment] 2023-03-11 10:02
The queue seems to be managed by multiprocessing-logging , and when we use it without parallizing the process there is no issue

I am unfortunately unable to reproduce the issue, but @llaville maybe you can help ?

**Comment by llaville** [comment] 2023-03-11 10:34
@jruere, /cc @nvuillam I'll be short in time, and did not provide any more help this afternoon until tomorrow morning !

But here is a quick steps to follows : 

1. Clone my repository `git clone https://github.com/llaville/php-compatinfo-db.git` (master branch)
1. Download Megalinter v6.20.1 docker image (PHP flavor image) => `docker pull oxsecurity/megalinter-php:v6`
1. Run following command `sudo rm -rf megalinter-reports/ && time docker run --rm -v /var/run/docker.sock:/var/run/docker.sock:rw -v $(pwd):/tmp/lint:rw oxsecurity/megalinter-php:v6`

As I've disable PARALLEL mode in my config file => https://github.com/llaville/php-compatinfo-db/blob/master/.mega-linter.yml#L38
You must enable it to see results !

**Comment by llaville** [comment] 2023-03-11 10:36
My platform is : 
- Docker version 23.0.1, build a5ee5b1
- Ubuntu 22.04.2 LTS (GNU/Linux 5.15.90.1-microsoft-standard-WSL2 x86_64)

**Comment by jruere** [comment] 2023-03-11 10:50
Thanks for the help!

**Comment by llaville** [comment] 2023-04-16 04:22
@jruere is there some news ?

**Comment by jruere** [comment] 2023-04-16 07:21
I completely forgot! I'm not available next week I'll take a note to work on this the other week.

Sorry for the delay.

**Comment by llaville** [comment] 2023-05-14 05:20
I supposed you've still not work on this purpose ?

I'm sad, because performance of MegaLinter when PARALLEL mode is disabled is poor, especially when we we lot of files.
E.g: 

![MegaLinter_Parallel_On](https://github.com/jruere/multiprocessing-logging/assets/364342/3f6a5b2d-3a74-4a88-a2df-63b272288733)

**Comment by zerocewl** [comment] 2023-12-15 18:18
Any updates?

**Comment by llaville** [comment] 2024-02-08 12:19
No news since a very long time. 

BTW, as I've migrated from MegaLinter v6 to v7 today, I've no more PARALLEL issue.

Certainly because MegaLinter v6 use Python 3.11, while MegaLinter v 7 [use Python 3.12](https://github.com/oxsecurity/megalinter/blob/v7.8.0/Dockerfile#L52)

@nvuillam You should close this report !

**Comment by nvuillam** [comment] 2024-02-08 12:58
@llaville i think the fix has been released :)

**Closed as completed** 2024-02-08 12:58 UTC
