### ISSUE TITLE
handle is closed error in Python 3.9.13

### ISSUE THREAD

**Issue by dstansby** [jruere/multiprocessing-logging#56] opened 2022-06-10 13:14 UTC
When using `multiprocessing-logging` in tandem with some code that has a `Pool`, I'm seeing a new error when upgrading from Python 3.9.12 to 3.9.13. The error messages are like:
```python
File "D:\a\cellfinder\cellfinder\.tox\py39-\lib\site-packages\multiprocessing_logging.py", line 81, in _receive
  record = self.queue.get(timeout=0.2)
File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\multiprocessing\queues.py", line 113, in get
  if not self._poll(timeout):
File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\multiprocessing\connection.py", line 260, in poll
  self._check_closed()
OSError: [WinError 6] The handle is invalid
File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\multiprocessing\connection.py", line 335, in _poll
  return bool(wait([self], timeout))
File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\multiprocessing\connection.py", line 888, in wait
  ov.cancel()
File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\multiprocessing\connection.py", line 335, in _poll
  return bool(wait([self], timeout))
File "D:\a\cellfinder\cellfinder\.tox\py39-\lib\site-packages\multiprocessing_logging.py", line 81, in _receive
  record = self.queue.get(timeout=0.2)
OSError: [WinError 6] The handle is invalid
OSError: handle is closed
```
and they go on pretty much indefinitely because they're in an infinite `while` loop in `multiprocessing_logging.py`. I'm afraid I haven't had time to try and get a reproducible example together, but I can confirm this is definitely isn't an issue on Python 3.9.12 and is an issue on 3.9.13. Looking down the Python changelog, my best guess is it's https://github.com/python/cpython/pull/31913 that has caused this.

To fix this, perhpas the exception handling in the lines below needs to be updated to catch the `OSError` being thrown?

https://github.com/jruere/multiprocessing-logging/blob/eaf924b10dcfe1360cfa6c8d9d5ed09945277cd3/multiprocessing_logging.py#L83-L90

**Comment by jruere** [comment] 2022-06-10 14:44
Thank you for reporting this.

In the receive loop, it should probably raise in the catch for anything.

I'll try to reproduce in a test using that version of python.

**Comment by jruere** [comment] 2022-06-12 16:13
Failed to reproduce, so far...

@dstansby  Could you provide code to reproduce the problem.

I'm having a hard time reproducing https://github.com/python/cpython/pull/31913 as it happens on shutdown...

**Comment by dervan** [comment] 2022-06-30 11:09
I am not sure if it's helpful, but the same issue arises when changing python version from 3.10.4 to 3.10.5. Reproduces nicely on the testcase of @dstansby too.

**Comment by nvuillam** [comment] 2022-06-30 22:43
Same error with Python 3.10.5 :/

**Comment by sspencer-hubble** [comment] 2022-07-06 15:02
It appears that the fix for this bug is to either add `OSError` to the list of error types on https://github.com/jruere/multiprocessing-logging/blob/3449c4e785bb61c99111c05e69c2dba0c2ab6cd1/multiprocessing_logging.py#L83

Or, move this line out of the `except` statement: https://github.com/jruere/multiprocessing-logging/blob/3449c4e785bb61c99111c05e69c2dba0c2ab6cd1/multiprocessing_logging.py#L14

**Comment by 3raser95** [comment] 2022-08-03 11:02
Any update on this? Don't mean to rush but it's just annoying when running a dev server and every time I make a change in my code these errors go on for maybe 5-10 seconds before the server reloads and I can continue testing.

**Comment by jruere** [comment] 2022-08-04 13:53
I'm sorry I've not been able to work on this project. I'm really swamped. :(

**Comment by sspencer-hubble** [comment] 2022-08-04 14:49
I got distracted with other things.  I'll put in a PR tonight with my fix for review.

**Comment by shellster** [comment] 2022-08-04 22:19
https://github.com/jruere/multiprocessing-logging/pull/57

Here's the pull mentioned by my other account.  Probably not suitable for merging as-is, but at least it will give people an idea on what needs to be fixed for their version.

**Comment by jweyrich** [comment] 2022-08-10 22:07
We're also having this issue.

**Comment by nvuillam** [comment] 2022-11-03 22:45
Any news about this issue ?
It prevents me to upgrase base docker image of [MegaLinter](https://oxsecurity.github.io/megalinter/latest/) :(

**Comment by jruere** [comment] 2022-11-11 09:36
So sorry, I've not had time to work on this.

**Comment by AlexLinus** [comment] 2022-11-30 14:49
Same issue on Python 3.10.8

**Comment by bloomen** [comment] 2022-12-12 03:49
@jruere Submitted a PR for this: https://github.com/jruere/multiprocessing-logging/pull/58 Thanks

**Comment by jruere** [comment] 2022-12-19 17:06
#58 was merged. I'll release this week.

**Comment by nvuillam** [comment] 2022-12-24 17:03
@jruere any news about when you plan to release the new version ? :)

**Comment by AlexLinus** [comment] 2023-01-03 06:10
@jruere Hi. Do you have any news when the new version will be released? )

**Comment by jruere** [comment] 2023-01-03 11:55
I need to do something to be able to push to PyPI and then I'll release.

Sorry for the delay. I'll do it ASAP.

**Comment by nvuillam** [comment] 2023-01-03 19:42
@jruere in order to simplify the next releases (and save you time !), you may define a Github Action that will automatically publish to PyPI, all you need is a PyPI token that you can define in the repository secrets

Example here with [github-dependents-info](https://github.com/nvuillam/github-dependents-info) : https://github.com/nvuillam/github-dependents-info/blob/main/.github/workflows/release.yml

**Comment by nvuillam** [comment] 2023-01-08 18:22
@jruere I totally understand the lack of time to maintain our Open-Source apps (I suffer from that myself), and that's the game to wait for maintainers availability, but I really need to have a delivery date for the new version because it prevents MegaLinter to upgrade python version (so some linters latest versions can not be used)

Please can you provide a date for the new version ? If you are not available soon that's of course totally ok, but I need to know it so I can use a workaround (that could be use multiprocessing-logging locally, or create a hard-fork that I'll maintain)

Many thanks for your reply :)

**Comment by AlexLinus** [comment] 2023-01-19 07:31
@jruere Hi. Do you have any news?

**Comment by jruere** [comment] 2023-01-24 19:50
I'm so sorry for the delay. I'll try to get it done this week. :(

**Comment by miohtama** [comment] 2023-01-25 13:17
Happy to help with the maintenance of the project if needed.

**Comment by miohtama** [comment] 2023-01-26 08:06
I just confirmed that installing the master directly from Github fixed my issue https://github.com/jruere/multiprocessing-logging/issues/60

Poetry dependency line example if someone needs a quick fix:

```
multiprocessing-logging = { git = "https://github.com/jruere/multiprocessing-logging.git", rev = "bc18e092af78d95781c57e3dffbb183da6882031" }
```

**Comment by bdovaz** [comment] 2023-02-01 13:52
Any news on that release @jruere? Thanks!

**Comment by JamesGDiaz** [comment] 2023-02-04 19:55
You don't need to wait for a Pypi release to install the new version
Just use `pip install "git+https://github.com/jruere/multiprocessing-logging.git#egg=multiprocessing_logging"`

**Comment by nvuillam** [comment] 2023-02-04 21:01
For security reason I'd really need an official version instead of using a git repo url, which content can change anytime

**Comment by JamesGDiaz** [comment] 2023-02-04 22:31
> For security reason I'd really need an official version instead of using a git repo url, which content can change anytime

You can fork the repo then, the wonders of open source software

**Comment by jruere** [comment] 2023-02-05 17:08
Released!

Apologies for the delay!!!

**Closed by jruere** 2023-02-05 17:08 UTC
